// vue/vue-router-test/src/components/Home.vue
<template>
  <div>
    <h2>
      欢迎使用vuejs
    </h2>
    <div>
      <h2 v-if="islogin">当前用户:{{curruser.name}}</h2>
      <a role="button" v-show="!islogin" class="btn btn-primary btn-lg" href="#/login">登录</a>
      <a role="button" class="btn btn-primary btn-lg" href="#/users">人员管理</a>
    </div>
  </div>
</template>

<script>
  export default {
    props:{
      islogin:{
        type:Boolean,
        default:false
      },
      curruser:{
        type:Object,
        default:{}
      },
      userlist:{}
    },
    data:function(){
      return {
      } ;
    },
    methods:{
      goToLogin:function(){
        // this.$emit('login','2222222222222222') ;
        this.$dispatch('login','111111111111111') ;
      },
      goToUsers:function(){
        this.$dispatch('goToUsers') ;
      }
    }
  }
</script>

// react/react-router/src/components/Home.jsx
var React = require('react')

var Home = React.createClass({
	componentDidMount:function(){
		// console.log(this)
	},
	render:function(){
		return (
			<div>
				<h2>Demo of React-router</h2>
				<div>
					{this.props.islogin && <h2 >当前用户:{this.props.curruser.name} </h2>}
					{!this.props.islogin && <a role="button" v-show="!islogin" className="btn btn-primary btn-lg" href="#/login">登录</a>}&nbsp; &nbsp;    
					<a role="button" className="btn btn-primary btn-lg" href="#/users">人员管理</a>
			  	</div>
			</div>
		)
	}
})

module.exports = Home
