// vue/vue-router-test/src/components/Login.vue
<template>
	<form action="#" class="form-signin">
		<h2 class="form-signin-heading">请登录</h2>
		<input type="text"  class="form-control" placeholder="编号" v-model="id">
		<input type="text"  class="form-control" placeholder="姓名" required autofocus v-model="name">
		<input type="text"  class="form-control" placeholder="电话" v-model="tel">
		<input type="text"  class="form-control" placeholder="年龄" v-model="age">
		<div class="checkbox">
			<label><input type="checkbox" value="remember-me">记住密码</label>
		</div>
		<button class="btn btn-primary btn-lg btn-block" type="button" v-on:click="login">登录</button>
		<button class="btn btn-default  btn-lg btn-block" type="button" v-on:click="back">返回</button>
	</form>
</template>

<script>
	export default {
		props:{
			islogin:{
				type:Boolean,
				default:false
			},
			userlist:{
				type:Array,
				default:[]
			},
			curruser:null
		},
		data () {
			return {
				id:'',
				name:'',
				tel:'137523747**',
				age:'2*'
			} 
		},
		methods:{
			login (){
				var self = this 
				var u = {
					id:self.id,
					name:self.name,
					tel:self.tel,
					age:self.age
				} ;
				self.userlist.push(u) 
				self.islogin = true 
				self.curruser = u ;
				window.history.go(-1) 
			},
			back (){
				window.history.go(-1) 
			}
		}
	}
</script>

// react/react-router/src/components/Login.jsx
var React = require('../../node_modules/react/dist/react-with-addons.js');

var Login = React.createClass({
	// 双向绑定
	mixins: [React.addons.LinkedStateMixin],
	getInitialState:function(){
		return {
			id:'',
			name:'',
			tel:'137523747',
			age:''
		}
	},
	loginClick:function(){
		var self = this 
		var u = {
			id:self.state.id,
			name:self.state.name,
			tel:self.state.tel,
			age:self.state.age
		} ;
		self.props.methods.login(u)
		this.backClick()
	},
	backClick:function(){
		window.history.go(-1)
	},
	render:function(){

		return (
			<form action="#" className="form-signin">
				<h2 className="form-signin-heading">请登录</h2>
				<input type="text"  className="form-control" placeholder="编号" valueLink={this.linkState('id')}/>
				<input type="text"  className="form-control" placeholder="姓名" required autofocus valueLink={this.linkState('name')}/>
				<input type="tel"  className="form-control" placeholder="电话"valueLink={this.linkState('tel')}/>
				<input type="tel"  className="form-control" placeholder="年龄" valueLink={this.linkState('age')}/>
				<div className="checkbox">
					<label><input type="checkbox" value="remember-me"/>记住密码</label>
				</div>
				<button className="btn btn-primary btn-lg btn-block" type="button" onClick={this.loginClick}>登录</button>
				<button className="btn btn-default  btn-lg btn-block" type="button" onClick={this.backClick}>返回</button>
			</form>
		)
	}
})

module.exports = Login
