// vue/vue-router-test/src/components/Userlist.vue
<template>
	<table class="table">
      <tr>
        <td>编号</td>
        <td>姓名</td>
        <td>电话</td>
        <td>年龄</td>
        <td>操作</td>
      </tr>
      <tr v-for="user in userlist" track-by="id">
        <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.tel }}</td>
            <td>{{ user.age }}</td>
            <td><button type="button" class="btn btn-danger" v-on:click="deleteUser" userid="{{ user.id }}">删除</button></td>
      </tr>
    </table>
</template>

<script>
export default {
  props: {
  	'userlist':{
  		type:Array,
  		default:[]
  	}
  },
  methods:{
  	deleteUser:function(event){
  		var target = event.target ;
  		var id = target.getAttribute('userid') 
  		if(!id) return ;
  		// var userList = this.userlist ;
  		// if(!userList || !userList.length){
  		//   return 
  		// }
  		// for(var i = 0 ; i < userList.length ; i++){
  		//   var u = userList[i]
  		//   if(u.id == id){
  		//     userList.splice(i,1)
  		//     break
  		//   }
  		// }
  		this.$dispatch('deleteUser',id)
  	}
  }
}
</script>

// react/react-router/src/components/UserList.jsx
var React = require('react')

var UserList = React.createClass({
	deleteUser:function(id){
		if(!id) return 
		this.props.deleteUser(id)
	},
	render:function(){
		var self = this
		var userlist = this.props.userlist
		var list = [] 
		
		if(userlist.length){
			for(var i = 0 ; i < userlist.length ; i++){
				var user = userlist[i]
				list.push(<tr key={user.id}>
			        <td>{ user.id }</td>
			            <td>{ user.name }</td>
			            <td>{ user.tel }</td>
			            <td>{ user.age }</td>
			            <td><button type="button" className="btn btn-danger" onClick={self.deleteUser.bind(self,user.id)} >删除</button></td>
			      </tr>)
			}
		}

		return (
			<table className="table">
			      <tbody>
			      	<tr>
			      	  <td>编号</td>
			      	  <td>姓名</td>
			      	  <td>电话</td>
			      	  <td>年龄</td>
			      	  <td>操作</td>
			      	</tr>
			      	{ list }
			      </tbody>
			</table>
		)
	}
})

module.exports = UserList
